- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install aptitude for Ansible
      raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)

- hosts: all
  gather_facts: true

- hosts: all
  gather_facts: false
  become: true
  tasks:    
    - apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    - apt_key: url=https://nvidia.github.io/nvidia-container-runtime/gpgkey state=present
    - get_url: url=https://nvidia.github.io/nvidia-container-runtime/ubuntu20.04/nvidia-container-runtime.list dest=/etc/apt/sources.list.d/nvidia-container-runtime.list
    - apt_repository: repo={{ item }} state=present
      with_items:
        - deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted
        - deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted
        - deb http://us.archive.ubuntu.com/ubuntu/ focal universe
        - deb http://us.archive.ubuntu.com/ubuntu/ focal-updates universe
        - deb http://us.archive.ubuntu.com/ubuntu/ focal multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ focal-updates multiverse
        - deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
        - deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    - package: name={{ item }} state=latest
      with_items:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - curl
      - software-properties-common
      - ubuntu-drivers-common
      - net-tools
      - docker-ce 
      - docker-ce-cli
      - containerd.io
    - command: ubuntu-drivers autoinstall