- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Install aptitude for Ansible
      raw: test -e /usr/bin/aptitude || (apt -y update && apt install -y aptitude)

- hosts: all
  gather_facts: true

- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: install microk8s
      command: snap install microk8s --classic
    - name: allow firewall pod-to-pod and pod-to-internet communication
      ufw:
        direction: in
        interface: cni0
        rule: allow
    - name: allow firewall pod-to-pod and pod-to-internet communication
      ufw:
        direction: out
        interface: cni0
        rule: allow
    - name: allow firewall pod-to-pod and pod-to-internet communication
      ufw:
        state: enabled
        direction: routed
    - name: enable addons
      command: microk8s enable dns dashboard storage
    - apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
    - apt_key: url=https://baltocdn.com/helm/signing.asc state=present
    - apt_repository: repo={{ item }} state=present
      with_items:
        - deb http://apt.kubernetes.io/ kubernetes-xenial main
        - deb https://baltocdn.com/helm/stable/debian/ all main
    - package: name={{ item }} state=latest
      with_items:
        - kubectl        
        - helm
    - group: name=sudo state=present
    - user: name={{ ansible_user }} shell=/bin/bash groups=sudo,microk8s append=yes
    - lineinfile: "dest=/etc/sudoers state=present line='%sudo ALL=(ALL) NOPASSWD: ALL'"
    - name: 'fix permission for microk8s'
      command: sudo usermod -a -G microk8s {{ ansible_user }}
    - name: 'fix permission for microk8s'
      command: sudo chown -f -R {{ ansible_user }} ~/.kube